#!/bin/bash
say -v "Kathy" "Water...fire... earth... apples.. lemons.. le mons" -r 300
say -v "Deranged" "What do you want? What do you want from me... a prize? a fucking prize? Is that what you want?"
exit
