#!/bin/bash
say -v "Bubbles" "Water...fire... earth... apples.. lemons... le mons"
say -v "Deranged" "What do you want? What do you want from me... a prize? a fucking prize? Is that what you want?"
say -v "Junior" "I want to fiddle my dandy. Iwant to feel more than a lick.. a tongue against my inner thighs. I want to feel enlightened. in my labia. I want to feel it tickle. I want to feel wanted"
exit
