#!/bin/bash
say -v "Agnes" "Do you even lift?" -r 200 | echo "How are you?"
say -v "deranged" "No, I do not. The only curls I do are in front of the toilet as I vomit my dreams." | echo "I'm so lonely"
say -v "Agnes" "oh, okay." | echo "I'm sorry for you,"
say -v "Agnes" " That's, um, great, I guess." -r 300
echo "I don't really know how to properly respond."
exit
